In [1]:
import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt
from sklearn import linear_model
from numpy.linalg import inv

In [5]:
vec = np.random.randn(3,4)
print(vec)
norm = np.linalg.norm(vec, axis=0)
print(norm)
vec /= norm
print(vec)

[[ 0.12044376 -0.99308561  0.47298314 -2.04881772]
 [-0.50248454  0.59408672 -1.17862479 -0.93292657]
 [-0.80057768 -1.08932733  0.456836   -0.97080444]]
[0.95284942 1.58927407 1.34965498 2.45162544]
[[ 0.12640377 -0.62486743  0.35044744 -0.83569769]
 [-0.52734936  0.37381011 -0.87327858 -0.38053389]
 [-0.84019327 -0.68542446  0.33848354 -0.395984  ]]


In [ ]:
a.dot